spring:
  application:
    name: genealogy

  datasource:
    url: jdbc:postgresql://localhost:5432/genealogy_db
    username: admin
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always